from typing import Any, Dict, List, Optional, Protocol


class Client(Protocol):
    def open_by_key(self, key: str) -> 'Spreadsheet': ...
    def open(self, title: str) -> 'Spreadsheet': ...


class Spreadsheet(Protocol):
    def worksheet(self, name: str) -> 'Worksheet': ...
    def worksheets(self) -> List['Worksheet']: ...


class Worksheet(Protocol):
    def get_all_records(self) -> List[Dict[str, Any]]: ...
    def update_cell(self, row: int, col: int, value: Any) -> None: ...
    def get(self, range_name: str) -> List[List[Any]]: ...


def authorize(credentials: Any) -> Client: ...

def service_account(filename: Optional[str] = ...) -> Client: ...
